{{- $namespace := print $.Values.global.pattern "-" $.Values.clusterGroup.name }}
{{- /*
  We first check if projects are defined as a map.  If it is we call
  our helper function in _helpers.tpl to process the projects
  described in the values file. This is to support issue 
  https://github.com/validatedpatterns/common/issues/459 created by our customer.
*/ -}}
{{- /*
  This template block iterates over the appropriate list based on which value 
  was provided in the 'values.yaml' file, as enforced by the JSON Schema (oneOf).
*/ -}}
{{- $projects := list -}}

{{- if .Values.clusterGroup.projects }}
  {{- $projects = .Values.clusterGroup.projects -}}
{{- else if .Values.clusterGroup.argoProjects }}
  {{- $projects = .Values.clusterGroup.argoProjects -}}
{{- end }}

{{- if kindIs "map" $projects }}
{{- template "clustergroup.template.plumbing.projects.map" (list $projects $namespace $.Values.enabled) }}  
{{- else }}
{{- range $projects }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ . }}
  namespace: {{ $namespace }}
spec:
  description: "Pattern {{ . }}"
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - '*'
status: {}
---
{{- end }} {{- /* end range */ -}}
{{- end }} {{- /* end if map */ -}}
